#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow "Nginx HTTP"
sudo ufw allow "Nginx HTTPS"
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
