#!/usr/bin/env bash
# a file to auto configure the nginx
http {
	# contomize the header name
	sudo apt-get -y update
	sudo apt-get -y install nginx
	sudo sed -i "15i \\\tadd_header X-Served-By web-01;" /etc/nginx/nginx.conf
	#sudo sed -i "16i \\\tadd_header X-Served-By web-02;" /etc/nginx/nginx.conf
	sudo service nginx restart
}
