#!/usr/bin/env bash
# configures a new Ubuntu machine

# Install nginx on web-01 server
#sudo apt-get -y update
#sudo apt-get -y install nginx
web_1="sudo ssh ubuntu@54.210.53.70"
web_2="sudo ssh ubuntu@34.224.17.191"
#sudo apt-get -y update
#sudo apt-get -y install nginx

"$web_1" sudo sed -i "51i \\tadd_header X-Served-By 317203-web-01;\n"
/etc/nginx/sites-enabled/default

"$web_2" sudo sed -i "51i \\tadd_header X-Served-By 317203-web-02;\n"
/etc/nginx/sites-enabled/default
"$web_1" systemctl restart nginx
"$web_2" systemctl restart nginx
