#!/usr/bin/env bash
" Procss and PID file
terminator()
{
	rm /var/run/myscript.pid
	exit
}
echo "&&" > /var/run/myscript.pid
while((1))
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminator' SIGQUITgit
done
