#!/usr/bin/env bash
# Check some file attributes

if [ -e file ]
{
then
	echo "school file exists"
	if [ -s file ]
	{
	then
		echo "school file is empty
	}
	else
	{
		echo "school file is not empty"
	}
	if [ -f file ]
	{
	then
		echo "school file is a regular file
	}
	fi
}
else
{
	echo "school file does not exit"
}
fi

