#!/usr/bin/env bash
# Using while and case to print output

cases()
{
local i="$i"
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "back luck japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
}
i=1

while [ $i -le 20 ]
do
	echo "$i"
	cases $i
	((i++))
done
	




